### ISSUE TITLE
Please, Following Datas are Needed.

### ISSUE THREAD

**Issue by rezwanh001** [camigord/Self-Driving-Car-Nanodegree#1]
You have used `train.p` , `valid.p` and `test.p`. But I did not find your repository.
Please, give these datasets.
```
training_file = "traffic-signs-data/train.p"
validation_file= "traffic-signs-data/valid.p"
testing_file = "traffic-signs-data/test.p"
```

**Comment by camigord** [comment]
Hi, the dataset that I used is based on the [German Traffic Sign Dataset](http://benchmark.ini.rub.de/?section=gtsrb&subsection=dataset), but with the images already resized to 32x32. I can not upload the files because they are quite heavy, but maybe you can use this [link](https://d17h27t6h515a5.cloudfront.net/topher/2017/February/5898cd6f_traffic-signs-data/traffic-signs-data.zip) to download them.

**Comment by rezwanh001** [comment]
@camigord . Thank you.
